### ISSUE TITLE
Support for RHEL7

### ISSUE THREAD

**Issue by rikkuness** [emccode/puppet-scaleio#7]
Is there scope to expand this module to also cover Red Hat Enterprise Linux 7?

**Comment by clintonskitson** [comment]
The module currently does support RHEL7.  It is the documentation that needs to be updated to reference the added variable.  The main difference is in the package names where the suffix of the RPMs is .el7 instead of .el6.  The following variable can be added to your site.pp file below $version.  
$rpm_suffix = '.el7.x86_64'

Following this, update your node classifications with this declaration to ensure you apply the correct suffix to whichever node will be RHEL7.
rpm_suffix => $rpm_suffix,


See the following branch that has an example site.pp file for RHEL7.

**Comment by rikkuness** [comment]
Excellent! Thanks for the clarification on that.
